// @dart=2.12

library woocommerce_client;

import 'dart:convert';
import 'dart:io';
import "dart:collection";
import "dart:math";
import "dart:core";
import 'package:crypto/crypto.dart' as crypto;

import 'package:collection/collection.dart';
import 'package:http/http.dart';

part 'utils/query_string.dart';

part 'api_client.dart';
part 'api_helper.dart';
part 'api_exception.dart';
part 'auth/authentication.dart';
part 'auth/http_basic_auth.dart';
part 'auth/oauth.dart';

part 'client/client.dart';

part 'model/customer.dart';
part 'model/customer1.dart';
part 'model/customer1_billing.dart';
part 'model/customer1_shipping.dart';
part 'model/customer2.dart';
part 'model/customer_download.dart';
part 'model/customer_download_file.dart';
part 'model/data_continents.dart';
part 'model/data_continents_countries_inner.dart';
part 'model/data_continents_countries_inner_states_inner.dart';
part 'model/data_countries.dart';
part 'model/data_currencies.dart';
part 'model/data_index.dart';
part 'model/order_note.dart';
part 'model/order_note1.dart';
part 'model/payment_gateway.dart';
part 'model/payment_gateway1.dart';
part 'model/payment_gateway1_settings.dart';
part 'model/product.dart';
part 'model/product1.dart';
part 'model/product1_attributes_inner.dart';
part 'model/product1_categories_inner.dart';
part 'model/product1_default_attributes_inner.dart';
part 'model/product1_dimensions.dart';
part 'model/product1_downloads_inner.dart';
part 'model/product1_images_inner.dart';
part 'model/product1_tags_inner.dart';
part 'model/product_attribute.dart';
part 'model/product_attribute1.dart';
part 'model/product_attribute2.dart';
part 'model/product_attribute_term.dart';
part 'model/product_attribute_term1.dart';
part 'model/product_attribute_term2.dart';
part 'model/product_cat.dart';
part 'model/product_cat1.dart';
part 'model/product_cat1_image.dart';
part 'model/product_cat2.dart';
part 'model/product_review.dart';
part 'model/product_review1.dart';
part 'model/product_review2.dart';
part 'model/product_review_reviewer_avatar_urls.dart';
part 'model/product_shipping_class.dart';
part 'model/product_shipping_class1.dart';
part 'model/product_shipping_class2.dart';
part 'model/product_tag.dart';
part 'model/product_tag1.dart';
part 'model/product_tag2.dart';
part 'model/product_variation.dart';
part 'model/product_variation1.dart';
part 'model/product_variation1_dimensions.dart';
part 'model/product_variation1_image.dart';
part 'model/report.dart';
part 'model/report_coupon_total.dart';
part 'model/report_customer_total.dart';
part 'model/report_order_total.dart';
part 'model/report_product_total.dart';
part 'model/report_review_total.dart';
part 'model/sales_report_total.dart';
part 'model/sales_report.dart';
part 'model/setting.dart';
part 'model/setting_group.dart';
part 'model/shipping_method.dart';
part 'model/shipping_zone.dart';
part 'model/shipping_zone1.dart';
part 'model/shipping_zone_location.dart';
part 'model/shipping_zone_location1.dart';
part 'model/shipping_zone_method.dart';
part 'model/shipping_zone_method1.dart';
part 'model/shipping_zone_method1_settings.dart';
part 'model/shipping_zone_method2.dart';
part 'model/shop_coupon.dart';
part 'model/shop_coupon1.dart';
part 'model/shop_coupon1_meta_data_inner.dart';
part 'model/shop_order.dart';
part 'model/shop_order1.dart';
part 'model/shop_order1_billing.dart';
part 'model/shop_order1_coupon_lines_inner.dart';
part 'model/shop_order1_fee_lines_inner.dart';
part 'model/shop_order1_line_items_inner.dart';
part 'model/shop_order1_line_items_inner_meta_data_inner.dart';
part 'model/shop_order1_line_items_inner_taxes_inner.dart';
part 'model/shop_order1_shipping.dart';
part 'model/shop_order1_shipping_lines_inner.dart';
part 'model/shop_order1_shipping_lines_inner_taxes_inner.dart';
part 'model/shop_order_refund.dart';
part 'model/shop_order_refund1.dart';
part 'model/shop_order_refund_line_items_inner.dart';
part 'model/shop_order_refund_line_items_inner_taxes_inner.dart';
part 'model/shop_order_refunds_inner.dart';
part 'model/shop_order_tax_lines_inner.dart';
part 'model/system_status.dart';
part 'model/system_status_database.dart';
part 'model/system_status_environment.dart';
part 'model/system_status_security.dart';
part 'model/system_status_settings.dart';
part 'model/system_status_theme.dart';
part 'model/system_status_tool.dart';
part 'model/system_status_tool1.dart';
part 'model/tax.dart';
part 'model/tax1.dart';
part 'model/tax_class.dart';
part 'model/tax_class1.dart';
part 'model/top_sellers_report.dart';
part 'model/webhook.dart';
part 'model/webhook1.dart';
part 'model/webhook2.dart';

const _delimiters = {'csv': ',', 'ssv': ' ', 'tsv': '\t', 'pipes': '|'};
const _dateEpochMarker = 'epoch';
const _deepEquality = DeepCollectionEquality();
final _regList = RegExp(r'^List<(.*)>$');
final _regSet = RegExp(r'^Set<(.*)>$');
final _regMap = RegExp(r'^Map<String,(.*)>$');

bool _isEpochMarker(String? pattern) =>
    pattern == _dateEpochMarker || pattern == '/$_dateEpochMarker/';
